set -g status-position top
set -Fg 'status-format[1]' '#[bg=#{@colour_bg1}]#{p-1000: } '

if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status 2"

set-hook -g window-linked 'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status 2"'
set-hook -g window-unlinked 'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status 2"'
set-hook -g window-layout-changed 'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status 2"'
