# Nightfox colors for Tmux
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox.tmux

# Modified by me to make minimal status line.

set -g @colour_black "#393b44"
set -g @colour_red "#c94f6d"
set -g @colour_green "#81b29a"
set -g @colour_yellow "#dbc074"
set -g @colour_blue "#719cd6"
set -g @colour_magenta "#9d79d6"
set -g @colour_cyan "#63cdcf"
set -g @colour_white "#dfdfe0"
set -g @colour_orange "#f4a261"
set -g @colour_pink "#d67ad2"

set -g @colour_comment "#738091"

set -g @colour_bg0 "#131a24" # Dark bg (status line and float)
set -g @colour_bg1 "#192330" # Default bg
set -g @colour_bg2 "#212e3f" # Lighter bg (colorcolm folds)
set -g @colour_bg3 "#29394f" # Lighter bg (cursor line)
set -g @colour_bg4 "#39506d" # Conceal, border fg
set -g @colour_fg0 "#d6d6d7" # Lighter fg
set -g @colour_fg1 "#cdcecf" # Default fg
set -g @colour_fg2 "#aeafb0" # Darker fg (status line)
set -g @colour_fg3 "#71839b" # Darker fg (line numbers, fold colums)
set -g @colour_sel0 "#2b3b51" # Popup bg, visual selection bg
set -g @colour_sel1 "#3c5372" # Popup sel bg, search bg

set -g mode-style "fg=#{@colour_bg0},bg=#{@colour_fg2}"
set -g message-style "fg=#{@colour_bg0},bg=#{@colour_fg2}"
set -g message-command-style "fg=#{@colour_bg0},bg=#{@colour_fg2}"
set -g pane-border-style "fg=#{@colour_bg0}"
set -g pane-active-border-style "fg=#{@colour_bg3}"
set -g status-justify "centre"
set -g status-style "fg=#{@colour_fg2},bg=#{@colour_bg0}"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style "fg=#{@colour_fg2},bg=#{@colour_bg0}"
set -g status-right-style "fg=#{@colour_fg2},bg=#{@colour_bg0}"

set -g status-left " "
set -g status-left-length 10

set -g status-right "#[fg=#{@colour_blue} bold]session:#[fg=#{@colour_yellow} bold]#S  "

setw -g window-status-activity-style "underscore,fg=#{@colour_fg3},bg=#{@colour_bg0}"

setw -g window-status-current-style 'fg=#{@colour_fg2} bg=#{@colour_bg3}'
setw -g window-status-current-format '#[fg=#{@colour_bg1}]▏#[fg=#{@colour_fg2} bg=#{@colour_bg3} bold]#I #W #F#[fg=#{@colour_bg1}]▕'

setw -g window-status-style 'fg=#{@colour_fg2} bg=#{@colour_bg0}'
setw -g window-status-format '#[fg=#{@colour_bg1}]▏#[fg=#{@colour_fg2} bg=#{@colour_bg0} bold]#I #W #F#[fg=#{@colour_bg1}]▕'

setw -g window-status-separator ""
